// invitations
export const DECLINE_INVITATION = 'DECLINE_INVITATION';
export const ACCEPT_INVITATION = 'ACCEPT_INVITATION';
export const FETCHING_INVITATIONS = 'FETCHING_INVITATIONS';
export const FETCHING_INVITATIONS_ERROR = 'FETCHING_INVITATIONS_ERROR';
export const FETCHING_INVITATIONS_SUCCESS = 'FETCHING_INVITATIONS_SUCCESS';

// organized events
export const FETCHING_ORGANIZED = 'FETCHING_ORGANIZED';
export const FETCHING_ORGANIZED_ERROR ='FETCHING_ORGANIZED_ERROR';
export const FETCHING_ORGANIZED_SUCCESS = 'FETCHING_ORGANIZED_SUCCESS';

export const FETCHING_PARTICIPATIONS = 'FETCHING_PARTICIPATIONS';
export const FETCHING_PARTICIPATIONS_SUCCESS = 'FETCHING_PARTICIPATIONS_SUCCESS';
export const FETCHING_PARTICIPATIONS_ERROR = 'FETCHING_PARTICIPATIONS_ERROR';

// bookings
export const FETCHING_BOOKINGS = 'FETCHING_BOOKINGS';
export const FETCHING_BOOKINGS_ERROR = 'FETCHING_BOOKINGS_ERROR';
export const FETCHING_BOOKINGS_SUCCESS = 'FETCHING_BOOKINGS_SUCCESS';

// event search
export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const FETCHING_EVENTS_SUCCESS = 'FETCHING_EVENTS_SUCCESS';
export const FETCHING_EVENTS_ERROR = 'FETCHING_EVENTS_ERROR';

// schedules
export const GET_SCHEDULES_ERROR = 'GET_SCHEDULES_ERROR';
export const FETCHING_SCHEDULES_SUCCESS = 'FETCHING_SCHEDULES_SUCCESS';
export const FETCHING_SCHEDULES = 'FETCHING_SCHEDULES';
export const FETCH_SCHEDULE_ERROR = 'FETCH_SCHEDULE_ERROR';
export const FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS';
export const FETCHING_SCHEDULE = 'FETCHING_SCHEDULE';
export const UPDATING_SCHEDULE = 'UPDATING_SCHEDULE';
export const UPDATING_SCHEDULE_SUCCESS = 'UPDATING_SCHEDULE_SUCCESS';
export const UPDATING_SCHEDULE_ERROR = 'UPDATING_SCHEDULE_ERROR';
export const CREATING_SCHEDULE = 'CREATING_SCHEDULE';
export const CREATING_SCHEDULE_SUCCESS = 'CREATING_SCHEDULE_SUCCESS';
export const CREATING_SCHEDULE_ERROR = 'CREATING_SCHEDULE_ERROR';
export const SCHEDULE_DELETED = 'SCHEDULE_DELETED';
export const DELETING_SCHEDULE = 'DELETING_SCHEDULE';
export const DELETE_SCHEDULE_ERROR = 'DELETE_SCHEDULE_ERROR';

// locations
export const FETCHING_LOCATIONS = 'FETCHING_LOCATIONS';
export const FETCHING_LOCATIONS_SUCCESS = 'FETCHING_LOCATIONS_SUCCESS';
export const FETCHING_LOCATIONS_ERROR = 'FETCHING_LOCATIONS_ERROR';