// invitations
export const DECLINE_INVITATION = 'DECLINE_INVITATION';
export const ACCEPT_INVITATION = 'ACCEPT_INVITATION';
export const FETCHING_INVITATIONS = 'FETCHING_INVITATIONS';
export const FETCHING_INVITATIONS_ERROR = 'FETCHING_INVITATIONS_ERROR';
export const FETCHING_INVITATIONS_SUCCESS = 'FETCHING_INVITATIONS_SUCCESS';

// organized events
export const FETCHING_ORGANIZED = 'FETCHING_ORGANIZED';
export const FETCHING_ORGANIZED_ERROR ='FETCHING_ORGANIZED_ERROR';
export const FETCHING_ORGANIZED_SUCCESS = 'FETCHING_ORGANIZED_SUCCESS';

export const FETCHING_PARTICIPATIONS = 'FETCHING_PARTICIPATIONS';
export const FETCHING_PARTICIPATIONS_SUCCESS = 'FETCHING_PARTICIPATIONS_SUCCESS';
export const FETCHING_PARTICIPATIONS_ERROR = 'FETCHING_PARTICIPATIONS_ERROR';