module.exports = {
  locale: 'du',
  name: 'Dummy',
  general: {
    title: 'TestSite',
    editProfile: 'Edit Profile',
    logout: 'Log Out',
    myEvents: 'MY EVENTS',
    bookIceTime: 'BOOK',
    joinAGame: 'SEARCH',
  },
  filters: {
    anywhere: 'Anywhere',
    anytime: 'Anytime',
    eventType: 'Locations',
    demographic: 'Filter 2',
    moreFilters: 'Filter 3',
  },
  events: {
    hostedBy: 'hosted by',
    perSkater: 'per person',
    perGoalie: 'per person',
    registered: 'registered',
    skillLevel: 'Skill level',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    openTo: 'Open to',
    allGenders: 'aliens',
    males: 'everybody',
    females: 'you',
    owned: 'Disabled',
    joinAsSkater: 'Button 1',
    joinAsGoalie: 'Button 2',
    join: 'Button 3',
  },
};