module.exports = {
  locale: 'en',
  name: 'English',
  general: {
    title: 'ONERINK',
    editProfile: 'Edit Profile',
    logout: 'Log Out',
    myEvents: 'MY EVENTS',
    bookIceTime: 'BOOK ICE TIME',
    joinAGame: 'JOIN A GAME',
  },
  filters: {
    anywhere: 'Anywhere',
    anytime: 'Anytime',
    eventType: 'Event Type',
    demographic: 'Demographic',
    moreFilters: 'More Filters',
  },
  events: {
    hostedBy: 'hosted by',
    perSkater: 'per skater',
    perGoalie: 'per goalie',
    registered: 'registered',
    skillLevel: 'Skill level',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    openTo: 'Open to',
    allGenders: 'all genders',
    males: 'males',
    females: 'females',
    owned: 'Owned',
    joinAsSkater: 'Join as Skater',
    joinAsGoalie: 'Join as Goalie',
    join: 'Join',
  },
};